### ISSUE TITLE
Library problems

### ISSUE THREAD

**Issue by uixandy** [SFX-WoW/AceGUI-3.0_SFX-Widgets#30]
Hey there I get following report everytime I play the game:

354x ...dOns\AceGUI-3.0_SFX-Widgets\Widgets\SFX-Info-URL.lua:18: Cannot find a library instance of "AceGUI-3.0".
[string "=[C]"]: in function `error'
[string "@AAP-Core\lib\HereBeDragons\LibStub\LibStub.lua"]:23: in function `LibStub'
[string "@AceGUI-3.0_SFX-Widgets\Widgets\SFX-Info-URL.lua"]:18: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "AceGUI-3.0"."

I already uninstalled AAP, but the problem continues.

**Comment by StormFX** [comment]
This is an issue with AceGUI not being installed. Make sure you allow embedded libraries and/or that Ace3 is installed.
