### ISSUE TITLE
LUA Error in 3.4.1 Wrath Client

### ISSUE THREAD

**Issue by supere989** [SFX-WoW/AceGUI-3.0_SFX-Widgets#58]
### Game Flavor

Classic Era, Classic Wrath

### Game Version

3.4.1

### Add-On Version

1.2.7

### Description

Message: AceEvent30Frame:RegisterEvent(): AceEvent30Frame:RegisterEvent(): Attempt to register unknown event "WEEKLY_REWARDS_UPDATE"
Time: Mon Feb 27 19:47:06 2023
Count: 1
Stack: AceEvent30Frame:RegisterEvent(): AceEvent30Frame:RegisterEvent(): Attempt to register unknown event "WEEKLY_REWARDS_UPDATE"
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>

### Error Message

```text
Message: AceEvent30Frame:RegisterEvent(): AceEvent30Frame:RegisterEvent(): Attempt to register unknown event "WEEKLY_REWARDS_UPDATE"
Time: Mon Feb 27 19:47:06 2023
Count: 1
Stack: AceEvent30Frame:RegisterEvent(): AceEvent30Frame:RegisterEvent(): Attempt to register unknown event "WEEKLY_REWARDS_UPDATE"
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>
```

### Screenshots

![image](https://user-images.githubusercontent.com/6176562/221749082-2afb9461-6403-4241-9527-39208e8e71aa.png)

**Comment by StormFX** [comment]
This doesn't seem to be related to SFX Widgets.

**Comment by supere989** [comment]
Oh you are right, my bad.
